# {{ ansible_managed }}

version: '2.1'

services:

  # PHP App
  php:

    hostname: ${COMPOSE_PROJECT_NAME}

    container_name: ${COMPOSE_PROJECT_NAME}

    build:
      context: ./build
      dockerfile: Dockerfile-php
      args:
        P_UID: ${P_UID}
        P_GID: ${P_GID}

    image: ${COMPOSE_PROJECT_NAME}/nginx-php56

    restart: always

    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

    volumes:
      - ../php-app/www:/www:ro
      - ../php-app/www/app/storage:/www/app/storage:rw

    networks:
      - shared

networks:
  shared:
    external:
      name: shared
