# {{ ansible_managed }}

version: '2.1'

services:

  # Go App
  app:

    hostname: app.skyclerk.com

    container_name: app.skyclerk.com

    image: golang:1.11-alpine

    restart: always

    working_dir: /go/bin

    entrypoint: ./app.skyclerk.com

    volumes:
      - ./app:/go/bin

    expose:
      - "9090"

    logging:
      driver: "syslog"
      options:
        syslog-address: ${SYSLOG_HOST}
        tag: app.skyclerk.com

    networks:
      - shared

networks:
  shared:
    external:
      name: shared
