# {{ ansible_managed }}

version: '2.1'

services:

  # Go App
  app:

    hostname: app.skyclerk.com

    container_name: app.skyclerk.com

    image: golang:1.11-alpine

    restart: always

    working_dir: /go/bin

    entrypoint: ./app.skyclerk.com

    volumes:
      - ./app:/go/bin:ro
      - ./cache:/cache:rw
      - ./fonts:/fonts:ro
      - ./frontend:/frontend:ro
      - ./letsencrypt:/letsencrypt:rw

    ports:
      - "80:80"
      - "443:443"

    logging:
      driver: "syslog"
      options:
        syslog-address: ${SYSLOG_HOST}
        tag: app.skyclerk.com

    networks:
      - shared

  # TODO(spicer):
  # We should move it over to its own docker-compose so redis is not restarted
  # every time we deploy the app

  # Redis 4.0
  redis:

    image: redis:5.0.4

    restart: always

    hostname: redis.skyclerk.com

    container_name: redis.skyclerk.com

    ports:
      - "127.0.0.1:6379:6379"

    networks:
      - shared

networks:
  shared:
    external:
      name: shared
