---

# Setup base directory
- name: Setup {{ imaginary_site_dir }} as base directory
  file: path={{ imaginary_site_dir }} owner={{ site_user }} group={{ site_user }} mode=0755 state=directory

# Install docker-compose
- name: Install docker-compose
  template: src=docker-compose.yml dest={{ imaginary_site_dir }}/docker-compose.yml owner={{ site_user }} group={{ site_user }} mode=0644

# Install ENV File
- name: Install Docker ENV File
  template: src=docker-env dest={{ imaginary_site_dir }}/.env owner={{ site_user }} group={{ site_user }} mode=0644

# Pull docker
- name: Building image for {{ imaginary_site_dir }}
  command: docker-compose build
  args:
    chdir: "{{ imaginary_site_dir }}"

# Stop docker
- name: Stopping docker container for {{ imaginary_site_dir }}
  command: docker-compose down --remove-orphans
  args:
    chdir: "{{ imaginary_site_dir }}"

# Start docker
- name: Starting docker for {{ imaginary_site_dir }}
  command: docker-compose up -d
  args:
    chdir: "{{ imaginary_site_dir }}"
