---

# Setup base directory
- name: Setup {{ site_dir }} as base directory
  file: path={{ site_dir }} owner={{ login_user }} group={{ login_user }} mode=0755 state=directory

# Install docker-compose
- name: Install docker-compose
  template: src=docker-compose.yml dest={{ site_dir }}/docker-compose.yml owner={{ login_user }} group={{ login_user }} mode=0644

# Install ENV File
- name: Install Docker ENV File
  template: src=docker-env dest={{ site_dir }}/.env owner={{ login_user }} group={{ login_user }} mode=0644

# Create docker app directory
- name: Create docker app directory
  file: path={{ site_dir }}/app owner={{ login_user }} group={{ login_user }} mode=0755 state=directory

# Install Go App ENV File
- name: Install Go App ENV File
  template: src=app-env dest={{ site_dir }}/app/.env owner={{ login_user }} group={{ login_user }} mode=0644

# Install app.skyclerk.com binary
- name: Copying app.skyclerk.com binary to server(s)
  copy: src=../backend/builds/app.skyclerk.com dest={{ site_dir }}/app/app.skyclerk.com owner={{ login_user }} group={{ login_user }} mode=0755

# Install fonts
- name: Copying fonts to app directory.
  synchronize: src=../fonts/ dest={{ site_dir }}/fonts

# Install app.skyclerk.com frontend code.
- name: Copying app.skyclerk.com frontend code to server(s)
  synchronize: src=../frontend/dist/frontend/ dest={{ site_dir }}/frontend/

# Change owner of /frontend
- name: Change owner of {{ site_dir }}/frontend
  file: path={{ site_dir }}/frontend owner={{ login_user }} group={{ login_user }} recurse=yes
  become: yes
  become_user: root

# Change owner of /fonts
- name: Change owner of {{ site_dir }}/fonts
  file: path={{ site_dir }}/fonts owner={{ login_user }} group={{ login_user }} recurse=yes
  become: yes
  become_user: root

# Install centcom.skyclerk.com frontend code.
- name: Copying centcom.skyclerk.com frontend code to server(s)
  synchronize: src=../centcom/dist/centcom-skyclerk-com/ dest={{ site_dir }}/centcom/

# Change owner of /centcom
- name: Change owner of {{ site_dir }}/centcom
  file: path={{ site_dir }}/centcom owner={{ login_user }} group={{ login_user }} recurse=yes
  become: yes
  become_user: root
