---

# See if we have uploaded the binary for skyclerk yet.
- name: Register {{ site_dir }}/app/app.skyclerk.com
  stat: path={{ site_dir }}/app/app.skyclerk.com
  register: app_binary

# Pull docker
- name: Building image for {{ site_dir }}
  command: docker-compose build
  when: app_binary.stat.exists == True
  args:
    chdir: "{{ site_dir }}"

# Stop docker
- name: Stopping docker container for {{ site_dir }}
  command: docker-compose down --remove-orphans
  when: app_binary.stat.exists == True
  args:
    chdir: "{{ site_dir }}"

# Start docker
- name: Starting docker for {{ site_dir }}
  command: docker-compose up -d
  when: app_binary.stat.exists == True
  args:
    chdir: "{{ site_dir }}"
