version: '2.1'

services:

  # App
  web:

    hostname: ${COMPOSE_PROJECT_NAME}

    container_name: ${COMPOSE_PROJECT_NAME}

    image: golang:1.11-alpine

    working_dir: /go/src/backend

    entrypoint: go run main.go

    volumes:
      - ../:/go/src/backend

    expose:
      - "9090"

    networks:
      - shared

networks:
  shared:
    external:
      name: shared
