---

- name: Deploy backups for skyclerk.com to production
  
  hosts: web-servers

  become: yes
  
  become_user: root

  roles:
    - cloudmanic-backup
    
  vars_files:
    - "vars/env.yml"
    - "vars/all.yml"