---

- name: Deploys the server config for app.skyclerk.com to production (and imaginary.skyclerk.com)

  hosts: web-servers

  become: yes

  become_user: root

  roles:
    - bootstrap
    - users
    - docker-sites
    - docker-mysql
    - docker-nginx-proxy
    - imaginary

  vars_files:
    - "vars/env.yml"
    - "vars/all.yml"
