# {{ ansible_managed }}

version: "3"

services:

  # App
  app:
    hostname: ${COMPOSE_PROJECT_NAME}

    container_name: ${COMPOSE_PROJECT_NAME}

    image: h2non/imaginary:1.1.0

    environment:
      PORT: 9000
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

    command: -concurrency 50 -enable-url-source  -key "${API_KEY}"

    expose:
      - "9000"

    restart: ${RESTART}

    logging:
      driver: "syslog"
      options:
        syslog-address: ${SYSLOG_HOST}
        tag: ${VIRTUAL_HOST}

    networks:
      - shared

networks:
  shared:
    external:
      name: shared
